spring:
  application:
    name: demo-service
  main:
    web-application-type: reactive

server:
  port: 8080

logging:
  level:
    ROOT: ERROR
    org.demo: INFO

demo:
  connections:
    r2dbc:
      mssql:
        test-res:
          uri: r2dbc:sqlserver://sa@localhost:1433/test
          password: test